name: main_ve
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython=8.12.0
  - notebook=6.5.4
  - cookiecutter=1.7.3
  - git=2.40.0
  - requests=2.28.2
  - pip=23.0.1
  - mlflow=2.2.2
  - hydra-core=1.3.2
  - seaborn=0.12.2
  - pandas=1.5.3
  - scikit-learn=0.24.1
  - matplotlib=3.6.3
  - plotly=5.14.0
  - pillow=9.4.0
  - pandas-profiling=3.6.3
  - pyarrow=11.0.0
  - jupyter=1.0.0
  - jupyterlab=3.6.3
  - pytest=7.2.2
  - scipy=1.9.3
  - pip:
      - wandb==0.14.2
      - hydra-joblib-launcher==1.2.0
